/**
 * 29 CISA SCuBA Entra ID (AAD) control definitions.
 * Each control wired to its real evaluator function.
 */

import type { ControlDefinition } from '../types.js';
import { evaluateAAD_1_1 } from '../evaluators/entra-id/aad-1-legacy-auth.js';
import { evaluateAAD_2_1, evaluateAAD_2_3 } from '../evaluators/entra-id/aad-2-risk-policies.js';
import {
  evaluateAAD_3_1, evaluateAAD_3_2, evaluateAAD_3_3, evaluateAAD_3_4,
  evaluateAAD_3_5, evaluateAAD_3_6, evaluateAAD_3_7, evaluateAAD_3_8,
} from '../evaluators/entra-id/aad-3-mfa.js';
import { evaluateAAD_4_1 } from '../evaluators/entra-id/aad-4-logging.js';
import {
  evaluateAAD_5_1, evaluateAAD_5_2, evaluateAAD_5_3, evaluateAAD_5_4,
} from '../evaluators/entra-id/aad-5-applications.js';
import { evaluateAAD_6_1 } from '../evaluators/entra-id/aad-6-passwords.js';
import {
  evaluateAAD_7_1, evaluateAAD_7_2, evaluateAAD_7_3, evaluateAAD_7_4,
  evaluateAAD_7_5, evaluateAAD_7_6, evaluateAAD_7_7, evaluateAAD_7_8, evaluateAAD_7_9,
} from '../evaluators/entra-id/aad-7-privileged-roles.js';
import { evaluateAAD_8_1, evaluateAAD_8_2, evaluateAAD_8_3 } from '../evaluators/entra-id/aad-8-guest-access.js';

export const ENTRA_ID_CONTROLS: ControlDefinition[] = [
  // MS.AAD.1.x - Legacy Authentication
  {
    id: 'MS.AAD.1.1v1',
    product: 'AAD',
    description: 'Legacy authentication SHALL be blocked.',
    requirementLevel: 'SHALL',
    severity: 'Critical',
    nist80053: 'AC-7',
    evaluator: evaluateAAD_1_1,
    requiredPermissions: ['Policy.Read.All'],
  },

  // MS.AAD.2.x - Risk-Based Policies
  {
    id: 'MS.AAD.2.1v1',
    product: 'AAD',
    description: 'Users detected as high risk SHALL be blocked.',
    requirementLevel: 'SHALL',
    severity: 'Critical',
    nist80053: 'AC-7',
    evaluator: evaluateAAD_2_1,
    requiredPermissions: ['Policy.Read.All', 'IdentityRiskEvent.Read.All'],
  },
  {
    id: 'MS.AAD.2.3v1',
    product: 'AAD',
    description: 'Sign-ins detected as high risk SHALL be blocked.',
    requirementLevel: 'SHALL',
    severity: 'Critical',
    nist80053: 'AC-7',
    evaluator: evaluateAAD_2_3,
    requiredPermissions: ['Policy.Read.All', 'IdentityRiskEvent.Read.All'],
  },

  // MS.AAD.3.x - Multi-Factor Authentication
  {
    id: 'MS.AAD.3.1v1',
    product: 'AAD',
    description: 'Phishing-resistant MFA SHALL be required for all users.',
    requirementLevel: 'SHALL',
    severity: 'Critical',
    nist80053: 'IA-2(1)',
    evaluator: evaluateAAD_3_1,
    requiredPermissions: ['Policy.Read.All'],
  },
  {
    id: 'MS.AAD.3.2v1',
    product: 'AAD',
    description: 'If phishing-resistant MFA cannot be used, an MFA method from the list SHALL be used.',
    requirementLevel: 'SHOULD',
    severity: 'High',
    nist80053: 'IA-2(1)',
    evaluator: evaluateAAD_3_2,
    requiredPermissions: ['UserAuthenticationMethod.Read.All', 'AuditLog.Read.All'],
  },
  {
    id: 'MS.AAD.3.3v1',
    product: 'AAD',
    description: 'If phishing-resistant MFA has not been enforced, an alternative MFA method SHALL be enforced.',
    requirementLevel: 'SHOULD',
    severity: 'Medium',
    nist80053: 'IA-2(1)',
    evaluator: evaluateAAD_3_3,
    requiredPermissions: ['Policy.Read.All'],
  },
  {
    id: 'MS.AAD.3.4v1',
    product: 'AAD',
    description: 'The Authentication Methods Manage Migration feature SHALL be set to Migration Complete.',
    requirementLevel: 'SHALL',
    severity: 'Medium',
    nist80053: 'IA-2(1)',
    evaluator: evaluateAAD_3_4,
    requiredPermissions: ['Policy.Read.All'],
  },
  {
    id: 'MS.AAD.3.5v1',
    product: 'AAD',
    description: 'SMS or voice as an MFA option SHALL NOT be used.',
    requirementLevel: 'SHALL NOT',
    severity: 'High',
    nist80053: 'IA-2(1)',
    evaluator: evaluateAAD_3_5,
    requiredPermissions: ['Policy.Read.All'],
  },
  {
    id: 'MS.AAD.3.6v1',
    product: 'AAD',
    description: 'Phishing-resistant MFA SHALL be required for highly privileged roles.',
    requirementLevel: 'SHALL',
    severity: 'Critical',
    nist80053: 'IA-2(1)',
    evaluator: evaluateAAD_3_6,
    requiredPermissions: ['Policy.Read.All', 'RoleManagement.Read.Directory'],
  },
  {
    id: 'MS.AAD.3.7v1',
    product: 'AAD',
    description: 'Managed devices SHOULD be required for authentication.',
    requirementLevel: 'SHOULD',
    severity: 'Medium',
    nist80053: 'CM-6',
    evaluator: evaluateAAD_3_7,
    requiredPermissions: ['Policy.Read.All'],
  },
  {
    id: 'MS.AAD.3.8v1',
    product: 'AAD',
    description: 'Managed Devices SHOULD be required to register MFA.',
    requirementLevel: 'SHOULD',
    severity: 'Medium',
    nist80053: 'CM-6',
    evaluator: evaluateAAD_3_8,
    requiredPermissions: ['Policy.Read.All'],
  },

  // MS.AAD.4.x - Logging
  {
    id: 'MS.AAD.4.1v1',
    product: 'AAD',
    description: "Security logs SHALL be sent to the agency's SIEM.",
    requirementLevel: 'SHALL',
    severity: 'High',
    nist80053: 'AU-6',
    evaluator: evaluateAAD_4_1,
    requiredPermissions: ['AuditLog.Read.All', 'Directory.Read.All'],
  },

  // MS.AAD.5.x - Application Consent & Registration
  {
    id: 'MS.AAD.5.1v1',
    product: 'AAD',
    description: 'Only administrators SHALL be allowed to register applications.',
    requirementLevel: 'SHALL',
    severity: 'High',
    nist80053: 'CM-7',
    evaluator: evaluateAAD_5_1,
    requiredPermissions: ['Policy.Read.All'],
  },
  {
    id: 'MS.AAD.5.2v1',
    product: 'AAD',
    description: 'Only administrators SHALL be allowed to consent to applications.',
    requirementLevel: 'SHALL',
    severity: 'High',
    nist80053: 'CM-7',
    evaluator: evaluateAAD_5_2,
    requiredPermissions: ['Policy.Read.All'],
  },
  {
    id: 'MS.AAD.5.3v1',
    product: 'AAD',
    description: 'An admin consent workflow SHALL be enabled.',
    requirementLevel: 'SHOULD',
    severity: 'Medium',
    nist80053: 'CM-7',
    evaluator: evaluateAAD_5_3,
    requiredPermissions: ['Policy.Read.All'],
  },
  {
    id: 'MS.AAD.5.4v1',
    product: 'AAD',
    description: 'Group owners SHALL NOT be allowed to consent to applications.',
    requirementLevel: 'SHALL NOT',
    severity: 'Medium',
    nist80053: 'CM-7',
    evaluator: evaluateAAD_5_4,
    requiredPermissions: ['Policy.Read.All'],
  },

  // MS.AAD.6.x - Passwords
  {
    id: 'MS.AAD.6.1v1',
    product: 'AAD',
    description: 'User passwords SHALL NOT expire.',
    requirementLevel: 'SHALL NOT',
    severity: 'Medium',
    nist80053: 'IA-5',
    evaluator: evaluateAAD_6_1,
    requiredPermissions: ['Domain.Read.All'],
  },

  // MS.AAD.7.x - Privileged Roles & PIM
  {
    id: 'MS.AAD.7.1v1',
    product: 'AAD',
    description: 'A minimum of two users and a maximum of eight users SHALL be provisioned with the Global Administrator role.',
    requirementLevel: 'SHALL',
    severity: 'Critical',
    nist80053: 'AC-6(5)',
    evaluator: evaluateAAD_7_1,
    requiredPermissions: ['Directory.Read.All', 'RoleManagement.Read.Directory'],
  },
  {
    id: 'MS.AAD.7.2v1',
    product: 'AAD',
    description: 'Privileged users SHALL be assigned to Entra ID roles via PIM.',
    requirementLevel: 'SHALL',
    severity: 'High',
    nist80053: 'AC-6(5)',
    evaluator: evaluateAAD_7_2,
    requiredPermissions: ['RoleManagement.Read.Directory', 'RoleEligibilitySchedule.Read.Directory'],
  },
  {
    id: 'MS.AAD.7.3v1',
    product: 'AAD',
    description: 'Activation of the Global Administrator role SHALL require approval.',
    requirementLevel: 'SHOULD',
    severity: 'High',
    nist80053: 'AC-6(5)',
    evaluator: evaluateAAD_7_3,
    requiredPermissions: ['RoleManagement.Read.Directory'],
  },
  {
    id: 'MS.AAD.7.4v1',
    product: 'AAD',
    description: 'Eligible and active role assignments SHALL be audited monthly.',
    requirementLevel: 'SHOULD',
    severity: 'Medium',
    nist80053: 'AC-6(5)',
    evaluator: evaluateAAD_7_4,
    requiredPermissions: ['RoleManagement.Read.Directory'],
  },
  {
    id: 'MS.AAD.7.5v1',
    product: 'AAD',
    description: 'Permanent active role assignments SHALL NOT be allowed.',
    requirementLevel: 'SHOULD',
    severity: 'High',
    nist80053: 'AC-6(5)',
    evaluator: evaluateAAD_7_5,
    requiredPermissions: ['RoleManagement.Read.Directory'],
  },
  {
    id: 'MS.AAD.7.6v1',
    product: 'AAD',
    description: 'Highly privileged role assignments SHALL require MFA activation.',
    requirementLevel: 'SHOULD',
    severity: 'High',
    nist80053: 'AC-6(5)',
    evaluator: evaluateAAD_7_6,
    requiredPermissions: ['RoleManagement.Read.Directory'],
  },
  {
    id: 'MS.AAD.7.7v1',
    product: 'AAD',
    description: 'Provisioning users to highly privileged roles SHALL NOT occur outside of PIM.',
    requirementLevel: 'SHOULD',
    severity: 'High',
    nist80053: 'AC-6(5)',
    evaluator: evaluateAAD_7_7,
    requiredPermissions: ['RoleManagement.Read.Directory'],
  },
  {
    id: 'MS.AAD.7.8v1',
    product: 'AAD',
    description: 'Activation of highly privileged roles SHOULD trigger an alert.',
    requirementLevel: 'SHOULD',
    severity: 'Medium',
    nist80053: 'AC-6(5)',
    evaluator: evaluateAAD_7_8,
    requiredPermissions: ['RoleManagement.Read.Directory'],
  },
  {
    id: 'MS.AAD.7.9v1',
    product: 'AAD',
    description: 'User activation of the Global Administrator role SHALL require approval.',
    requirementLevel: 'SHOULD',
    severity: 'High',
    nist80053: 'AC-6(5)',
    evaluator: evaluateAAD_7_9,
    requiredPermissions: ['RoleManagement.Read.Directory'],
  },

  // MS.AAD.8.x - Guest Access
  {
    id: 'MS.AAD.8.1v1',
    product: 'AAD',
    description: 'Guest users SHOULD only be allowed access by specific organization admins.',
    requirementLevel: 'SHOULD',
    severity: 'High',
    nist80053: 'AC-3',
    evaluator: evaluateAAD_8_1,
    requiredPermissions: ['Policy.Read.All'],
  },
  {
    id: 'MS.AAD.8.2v1',
    product: 'AAD',
    description: 'Guest invites SHOULD only be allowed from specific admin roles.',
    requirementLevel: 'SHOULD',
    severity: 'High',
    nist80053: 'AC-3',
    evaluator: evaluateAAD_8_2,
    requiredPermissions: ['Policy.Read.All'],
  },
  {
    id: 'MS.AAD.8.3v1',
    product: 'AAD',
    description: 'Guest user access SHALL be restricted.',
    requirementLevel: 'SHOULD',
    severity: 'Medium',
    nist80053: 'AC-3',
    evaluator: evaluateAAD_8_3,
    requiredPermissions: ['Policy.Read.All'],
  },
];
