export const ERROR_CODES = {
  // Auth errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  MFA_NOT_COMPLETED: 'MFA_NOT_COMPLETED',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  // Tenant errors
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_ACCESS_DENIED: 'TENANT_ACCESS_DENIED',
  TENANT_DELETED: 'TENANT_DELETED',
  // Org errors
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  ORG_DELETED: 'ORG_DELETED',
  // Onboarding errors
  OAUTH_ERROR: 'OAUTH_ERROR',
  GDAP_ERROR: 'GDAP_ERROR',
  PROVISIONING_ERROR: 'PROVISIONING_ERROR',
  TENANT_ALREADY_EXISTS: 'TENANT_ALREADY_EXISTS',
  // System errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  KEYVAULT_ERROR: 'KEYVAULT_ERROR',
} as const;
